[server]
host = "localhost"
port = 9999

[display]
max_lines = 10000

[log_format]
pattern = "^\\[(?P<timestamp>.*?)\\]\\s*\\[(?P<level>\\w+)\\]\\s*(?P<message>.*)"

[colors.DEBUG]
bg = "#ed333b"
fg = "#33d17a"

[colors.INFO]
bg = "#33d17a"
fg = ""

[colors.WARNING]
bg = "#e66100"
fg = ""

[colors.ERROR]
bg = ""
fg = ""

[colors.CRITICAL]
bg = ""
fg = ""

[theme]
name = "dark_pink.xml"
