[server]
host = "localhost"
port = 9999

[display]
max_lines = 10000

[log_format]
pattern = "^(?:\\[(?P<index>\\d+)\\])?\\s*\\[(?P<timestamp>.*?)\\]\\s*\\[(?P<level>\\w+)\\](?:\\s*\\[(?P<module>\\w+)\\])?(?:\\s*\\[(?P<submodule>\\w+)\\])?\\s*(?P<message>.*)"

[colors.DEBUG]
bg = "#5e5c64"
fg = "#ffffff"

[colors.INFO]
bg = "#26a269"
fg = ""

[colors.WARNING]
bg = "#924400"
fg = ""

[colors.ERROR]
bg = "#f66151"
fg = ""

[colors.CRITICAL]
bg = "#a51d2d"
fg = ""

[theme]
name = "dark_pink.xml"
